[book]
title = "MAX31856 Driver Documentation"
language = "en"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/eiaro/esp-idf-components/tree/master/max31856"
edit-url-template = "https://github.com/eiaro/esp-idf-components/edit/master/max31856/docs/{path}"
mathjax-support = true
