[book]
title = "TXE81xx Driver Documentation"
language = "en"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/eiaro/esp-idf-components/tree/master/txe81xx"
edit-url-template = "https://github.com/eiaro/esp-idf-components/edit/master/txe81xx/docs/{path}"
mathjax-support = true
